### PR TITLE
Add laravel 11 support

### PR DESCRIPTION
**Pull request by mokhosh**
I haven't updated the readme as I'm not sure whether you will add this to a new tag or not. Can do that after confirming your decision.

### CODE REVIEW

**Review by alies-dev — APPROVED** [review]
Great, @mokhosh thanks a lot! I'm really glad that someone helped me to contribute to this package! 💪  


Based on https://github.com/psalm/psalm-plugin-laravel/actions/runs/8037576434/job/21955406945, don't we need to also install `orchestra/testbench` of 9/dev version?

**Comment by mokhosh** [comment]
No worries man, glad I could help.

Added Testbench 9 to Laravel 11 workflows.

**Comment by mokhosh** [comment]
We're out of composer dependency and github workflow issues.
We're getting some Psalm `RiskyTruthyFalsyComparison` errors in different tests, however.

**Comment by alies-dev** [comment]
closing in favour of https://github.com/psalm/psalm-plugin-laravel/pull/364

**Comment by mokhosh** [comment]
@alies-dev it's ok, man.

**Pull request closed without merging**
