### PR TITLE
Generic collection

### PR DESCRIPTION
**Pull request by mr-feek**
should close https://github.com/psalm/psalm-plugin-laravel/issues/23

based on my other prs so i can have testing...  Happy to  rebase after others get merged

### CODE REVIEW

**Comment by mr-feek** [comment]
This was based off of the [collection stub](https://github.com/nunomaduro/larastan/blob/master/stubs/Collection.stub) @canvural authored for larastan, but has a few additions. I suspect that this plugin for psalm is going to want a lot of the same stub files. Does it make sense  to maintain duplicates in each codebase? Is it worth extracting them out into their own codebase so they can be shared?

**Comment by vladyslavstartsev** [comment]
First of all, thanks for the job done.
Secondly, if will be nice to have separate repo for this, but ask for it first in larastan repo.

**Comment by muglug** [comment]
I think for the moment you could keep them here, until there’s more consolidation

**Comment by muglug** [comment]
Thanks!

**Pull request merged**
