### PR TITLE
feature: stubs for Factory and HasFactory

### LINKED ISSUE #155: [8.x] Support new Model::factory() syntax
**Is your feature request related to a problem? Please describe.**
The new Laravel 8 factory syntax is not yet supported, so Psalm cannot determine the type of `User::factory()->make()` or `User::factory()->count(2)->make()` (which is equivalent to `User::factory(2)->make()`).

For a `App\Models\User` model, factories are now defined as follows:

* the `HasFactory` trait is used in the `User` class, which adds a static `factory()` method
* the corresponding `Database\Factories\UserFactory` is instantiated and returned
* if a numeric value is passed to `factory()`, this implicitly sets the `count()` accordingly

See also: https://laravel.com/docs/8.x/database-testing#defining-model-factories

**Describe the solution you'd like**
Add support for these factories.

**Describe alternatives you've considered**
(None.)

**Additional context**
As a workaround, I have added `<directory name="tests"/>` folder to the `<psalm><projectFiles><ignoreFiles>` section in the `psalm.xml` configuration.

### PR DESCRIPTION
**Pull request by caugner**
Fixes #155.

~~⚠️ Blocked by https://github.com/vimeo/psalm/pull/6054 (already merged, but Psalm release pending).~~

### CODE REVIEW

**Comment by caugner** [comment]
@mr-feek I'm not sure why, but Psalm already seems to find out that `User::factory()` is of type `Database\Factories\UserFactory`. However, it doesn't seem to understand that `UserFactory::createOne()` returns a `User`, despite the stub in this PR.

Any ideas what I'm doing wrong?

**Comment by caugner** [comment]
Also, the test is failing, so I must have gotten something wrong:

```
Scanning files...
Analyzing files...


   ErrorException 

  Undefined array key 2

  at vendor/vimeo/psalm/src/Psalm/Internal/Analyzer/FunctionLikeAnalyzer.php:820
    816▕             if ($position === false) {
    817▕                 throw new \UnexpectedValueException('$position should not be false here');
    818▕             }
    819▕ 
  ➜ 820▕             if ($storage->params[$position]->by_ref) {
    821▕                 continue;
    822▕             }
    823▕ 
    824▕             if ($storage->params[$position]->promoted_property) {
```

Maybe I'm not allowed to declare `HasFactory::factory()` as `public static function factory($count = null, $state = [])`, when it reality is still is `public static function(...$parameters)` in 8.x and will only has the improved signature in Laravel 9.x?

**Comment by mr-feek** [comment]
I'm honestly not sure off the top of my head, I'd have to dig a bit into psalm to see what exactly is causing the crash. You might be able to do something fun with the (undocumented) `func_get_args` psalm syntax like I used here: https://github.com/psalm/psalm-plugin-laravel/blob/master/stubs/helpers.stubphp#L35

**Comment by caugner** [comment]
Blocked by: https://github.com/vimeo/psalm/pull/6054

**Comment by caugner** [comment]
https://github.com/vimeo/psalm/pull/6054 has been merged, but this will have to wait for the next Psalm release.

**Comment by caugner** [comment]
Closing this PR, because I have left the company that was using this package and for which I was doing this contribution as part of my daily work. :wave:

Apologies to anybody who may be disappointed, because they counted on this PR getting merged someday. :pray: 

Obviously, if anybody wants to base their contribution on this PR, feel free to do so! No attribution required.

**Comment by caugner** [comment]
Closing this PR, because I have left the company that was using this package and for which I was doing this contribution as part of my daily work. :wave:

Apologies to anybody who may be disappointed, because they counted on this PR getting merged someday. :pray: 

Obviously, if anybody wants to base their contribution on this PR, feel free to do so! No attribution required.

**Pull request closed without merging**
