### PR TITLE
Add stub for cache repository interface

### PR DESCRIPTION
**Pull request by Legion112**

### CODE REVIEW

**Comment by Legion112** [comment]
https://github.com/psalm/psalm-plugin-laravel/pull/236

**Comment by mr-feek** [comment]
Thanks for the pr @Legion112 ! Would you be willing to add a test case to verify the functionality?

**Comment by Legion112** [comment]
@mr-feek i have tested this on in my project on real cases. I asure you it work fine.
But later I could take a look at writing test.

**Comment by alies-dev** [comment]
this is finally released on 1.x branch :) 🎸 😀

**Pull request merged**
