### PR TITLE
Add support for later versions of IDE helper

### PR DESCRIPTION
**Pull request by ronb-lendesk**
Prior to this change, projects that used later versions (>=2.10) would have issues with compatibility if it's using this package. This change adds support for later versions of that IDE helper. It builds on a previous PR where the `FakeModelsCommand` class is switched based on the installed version of the later version for compatibility.

I'm sure I missed something so please let me know. :)

### CODE REVIEW

**Comment by ronb-lendesk** [comment]
@mr-feek Looks like github is back up again. Do you need to restart the actions?

**Comment by mr-feek** [comment]
@ronb-lendesk I think github is still a bit behind, the jobs are still marked as queued and won't let me cancel them to resubmit

**Comment by mr-feek** [comment]
@ronb-lendesk want to try pushing an empty commit? These github actions seem to be in a bad state due to their outage. they are stuck queued and i can't cancel them

**Comment by orklah** [comment]
closing/reopening seemed to do the trick :)

**Comment by mr-feek** [comment]
@ronb-lendesk this looks great. 2 things left to do:

1) Fix phpcs issues
2) Update the baseline for the laravel tests.

Are you up for these tasks?

**Comment by mr-feek** [comment]
Thanks a lot for the PR @ronb-lendesk -- I'm going to merge it to dev-master where hopefully people can test for the next week or so before cutting a new release!

**Comment by ronb-lendesk** [comment]
> Thanks a lot for the PR @ronb-lendesk -- I'm going to merge it to dev-master where hopefully people can test for the next week or so before cutting a new release!

Woohoo! Amazing. Thanks @mr-feek.

**Pull request merged**
