### PR TITLE
Psalm 5 support

### LINKED ISSUE #234: Support Psalm 5.0
It’s in beta now: https://github.com/vimeo/psalm/releases/tag/5.0.0-beta1

### PR DESCRIPTION
**Pull request by danog**
Fixes #234

### CODE REVIEW

**Comment by danog** [comment]
Tests are all passing!

**Comment by danog** [comment]
Fixes #234

**Comment by weirdan** [comment]
> Fixes #234

It has to be in the PR description

**Comment by danog** [comment]
Done!

**Comment by orklah** [comment]
Thanks!

**Comment by danog** [comment]
Hi @mr-feek, you think you could tag a release? :)

**Comment by mr-feek** [comment]
thanks for the PR! I'll cut a new release now

**Pull request merged**
