### PR TITLE
[2.x] Fix tests by dropping support for Laravel 7

### PR DESCRIPTION
**Pull request by caugner**
Fixes the "Install dependencies" step of the tests.

### CODE REVIEW

**Comment by caugner** [comment]
@mr-feek Eventually, I may have found the root cause for the failing tests: `barryvdh/laravel-ide-helper:2.9.2` and later require `laravel/framework:^8` which requires `illuminate/support:^8`. 

This indicates that your latest patch release (which surprised me a bit) included a breaking change (removing compatibility with Laravel 7). And since the Laravel 7 tests fail, we don't get to test the Laravel 8 side of the matrix.

I would suggest to revert the change and release another patch release (or re-release the previous patch release as a new patch release) , then remove Laravel 7 from the supported versions and bump the major version.

**Comment by mr-feek** [comment]
it wasn't my intention to remove support for laravel 7 -- I did not realize that change also occured in ide-helper. Let me figure out how to undo this.

**Comment by caugner** [comment]
> Let me figure out how to undo this.

@mr-feek Thanks for the swift response and the new patch release, it came just in time before our (Gitlab-)Dependabot noticed the release. :tada:

My suggestion would be to branch off `1` and to bump the major in `master`.

**Comment by mr-feek** [comment]
I would be super happy to just ditch ide-helper all together

**Comment by mr-feek** [comment]
I'm going to close this as I want to keep laravel 7 support for now. I took your require changes and put them in https://github.com/psalm/psalm-plugin-laravel/pull/151 .

thanks for noticing that!

**Pull request closed without merging**
