### PR TITLE
feature: support for polymorphic relations

### LINKED ISSUE #80: Support for polymorphic relations
**Describe the bug**
```
ERROR: TooManyTemplateParams - app/Context/Product/Models/FieldOfStudy.php:26:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(Event::class, 'product');


ERROR: TooManyTemplateParams - app/Context/Product/Models/ProductAttribute.php:23:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(
            Event::class,
            'assigned_attribute',
            'product_assigned_attributes'
        );


ERROR: TooManyTemplateParams - app/Context/Product/Types/Event/Models/Event.php:107:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Models\FieldOfStudy> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphToMany(
            FieldOfStudy::class,
            'product',
            'product_field_of_study',
            'product_uuid'
        )->withPivot('credit_hours');
```

**Impacted Versions**
`dev-master`

**Additional context**
@brendt reported here: https://github.com/psalm/psalm-plugin-laravel/issues/62#issuecomment-641062941

### PR DESCRIPTION
**Pull request by mr-feek**
Basic support for polymorphic relations, should close #80 cc @brendt

It isn't smart enough to figure out `MorphTo` models, I'm just leaving that as mixed for now. Feel free to pr that functionality!

### CODE REVIEW

**Comment by brendt** [comment]
Thanks! It seems to have fixed one of the errors I encountered, but these other three still exist:

```
ERROR: TooManyTemplateParams - app/Context/Product/Models/Concerns/HasProductAttributes.php:12:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Models\ProductAttribute> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphToMany(
            ProductAttribute::class,
            'assigned_attribute',
            'product_assigned_attributes',
            'assigned_attribute_uuid'
        );


ERROR: TooManyTemplateParams - app/Context/Product/Models/FieldOfStudy.php:26:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(Event::class, 'product');


ERROR: TooManyTemplateParams - app/Context/Product/Models/ProductAttribute.php:23:16 - Illuminate\Database\Eloquent\Relations\MorphToMany<App\Context\Product\Types\Event\Models\Event> has too many template params, expecting 0 (see https://psalm.dev/184)
        return $this->morphedByMany(
            Event::class,
            'assigned_attribute',
            'product_assigned_attributes'
        );
```

**Comment by brendt** [comment]
Let me know if you need a more comprehensive code snippet.

**Comment by mr-feek** [comment]
Ah I forgot `MorphToMany`, gimme a few!

**Comment by njaremko** [comment]
This is missing `MorphOne` support too :)

**Pull request merged**
