### PR TITLE
Run test suite on PHP 8.0 and 8.1

### PR DESCRIPTION
**Pull request by Nielsvanpach**
- Run test suite with PHP 8.0
- Shortened step names in workflow to make it readable on Github
- Cleanup of composer.json

### CODE REVIEW

**Comment by Nielsvanpach** [comment]
Hi there, any feedback on how to get this PR through?

**Comment by mr-feek** [comment]
@Nielsvanpach any idea why psalm is failing?

**Comment by Nielsvanpach** [comment]
Added an extra check, that should cover the psalm errors.

**Comment by Nielsvanpach** [comment]
In the meantime I've included 8.1 aswel in the tests

**Comment by Nielsvanpach** [comment]
Hi @mr-feek , what can I do for you to get this PR through? It has been quiet on this repo for some time, so I was wondering if there are any plans to continue maintaining this package? Thanks for all your work here!

**Comment by mr-feek** [comment]
hey @Nielsvanpach !!

Really need to get `master` passing CI tests again. I haven't had the time to do so, PRs would be very welcome 🤝

**Pull request merged**
